name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev,plot]
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Pytest
        run: pytest -q
